-- --------------------------------------------------------
-- Host:                         172.30.121.141
-- Server version:               8.0.30-0ubuntu0.20.04.2 - (Ubuntu)
-- Server OS:                    Linux
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for resday
DROP DATABASE IF EXISTS `resday`;
CREATE DATABASE IF NOT EXISTS `resday` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `resday`;

-- Dumping structure for table resday.posters
DROP TABLE IF EXISTS `posters`;
CREATE TABLE IF NOT EXISTS `posters` (
  `id` int NOT NULL AUTO_INCREMENT,
  `category` varchar(50) DEFAULT NULL,
  `number` varchar(50) DEFAULT NULL,
  `name` longtext,
  `title` longtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=320 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table resday.posters: ~0 rows (approximately)
/*!40000 ALTER TABLE `posters` DISABLE KEYS */;
REPLACE INTO `posters` (`id`, `category`, `number`, `name`, `title`) VALUES
	(1, 'UG', 'UG#01', 'Dr. Shubhra Mandal, MBBS Student', 'Comparison of King Vision™ videolaryngoscope channeled and non-channeled blades with direct laryngoscope for intubation in mannikin by medical students: a randomized manikin study [This Study was funded by UG Mentorship program'),
	(2, 'UG', 'UG#02', 'Bansal Bhavik, MBBS Student', 'Comparison of online content-based training with hands on mannequin based skill training on basic life support knowledge and skills among medical students'),
	(3, 'UG', 'UG#03', ' Aumkar Kishore Shah, MBBS Student', 'Generation and characterization of anti-HIV-1 human monoclonal antibodies from an India subtype-C infected long-term non-progressor'),
	(4, 'UG', 'UG#04', 'Parnika Nangla, MBBS Student, Department of Neurology', 'Peripheral nervous system involvement in SSPE – A parainfectious manifestation'),
	(5, 'UG', 'UG#05', 'Tamoghna Ghosh, MBBS Student, Department of Anatomy', 'Functional improvement of arthritic knee joints after intra-articular somatostatin injection in rats'),
	(6, 'UG', 'UG#06', 'Amit Kumar, MBBS Student', 'How founder mutations of Iran can help to unearth the hidden diseases in Indian Genome?'),
	(7, 'UG', 'UG#07', 'Jayashimman, MBBS Student', 'Idiopathic intracranial Hypertension – False localizing symptoms'),
	(8, 'UG', 'UG#08', 'Arunangshu Bhattacharyya, MBBS Student, Department of Obstetrics and Gynecology', 'First trimester serum alkaline phosphatase as a predictive marker for gestational diabetes mellitus: A retrospective study'),
	(9, 'UG', 'UG#09', 'Madhav Mohata, MBBS Student, Department of Biochemistry', 'Characterization of anti-CD20 encoding DmAb as a sustainable approach towards cost effective Immunotherapy'),
	(10, 'UG', 'UG#10', 'Asif Hasan, BSc Student', 'Post-COVID steroid induced osteonecrosis of the jaw'),
	(11, 'UG', 'UG#11', 'Alka Kumari, Bsc Student, Department of Centre of Dental Education and Research', 'Oral manifestations of COVID-19: A review'),
	(12, 'UG', 'UG#12', 'Vaishnavi Agnihotri Bsc Student, Department of CDER', 'Oral health status amongst the Borderline Security Force personnel and their family members'),
	(13, 'UG', 'UG#13', 'Wadiya Nikhil Hansraj BSc Student, Department of CDER', 'Perception regarding the tobacco dentifrice (Gulmanjan) amongst the people Visiting tobacco cessation clinic '),
	(14, 'SR', 'SR#01', 'Dr. Raktim Swarnakar, Department of Physical Medicine and Rehabilitation (PM&R) ', 'ReCOVer study: A Cross-sectional Observational Study to Identify the Rehabilitation Needs in Post-discharge COVID-19 Survivors'),
	(15, 'SR', 'SR#02', 'ThamizharasanDatchinamourthy, Senior Resident, Dept. of Anaesthesiology, Pain Medicine and Critical Care', 'Comparative Evaluation Of Continuous Infusion Versus Programmed Intermittent Bolus Techniques In Erector Spinae Plane Block In Modified Radical Mastectomy- A Randomised Controlled Trial'),
	(16, 'SR', 'SR#03', 'Nidhisha sadhwani, DM / MCh, Senior Resident, Department of ', 'Characteristics and operative management of lower lumbar vertebral (L4 and L5) burst fractures'),
	(17, 'SR', 'SR#04', 'Dr Akshata Rao, Senior Resident, Department of ', 'Study of Neurofilament light protein as a serum biomarker in Subjective cognitive decline'),
	(18, 'SR', 'SR#05', 'Bharathi Arunan, Senior Resident, Department of Medicine ', 'Central line associated blood stream infection (CLABSI): Effect of biofilms on outcomes'),
	(19, 'SR', 'SR#06', 'Rijuta, DM / MCh, Senior Resident, Department of Surgery ', 'Impact of Fluoro-Choline PET/CT in Reduction of PossibleFailed Parathyroidectomy in Primary Hyperparathyroidism'),
	(20, 'SR', 'SR#07', 'Rijuta Aphale, DM / MCh, Senior Resident, Department of Surgery', 'Aspergillosis Breast Attack- Gangrene of bilateral breasts'),
	(21, 'SR', 'SR#09', 'DeepaliAgarwal, Senior Resident, Department of Division of Public Health Dentisty, CDER', 'The effect of various Front of Pack nutrition labeling systems on willingness to consumption amongst the Indian population'),
	(22, 'SR', 'SR#10', 'Pankush Gupta, DM / MCh, Senior Resident, Department of Obstetrics and Gynaecology', 'Evaluation Of Diagnostic Potential OfHysteroscopy, Histopathology And MolecularMicrobiology In Chronic Endometritis InWomen With Tubal And Unexplained InfertilityUndergoing IVF – A Prospective Cohort Study'),
	(23, 'SR', 'SR#11', 'Pankush Gupta, DM / MCh, Senior Resident, Department of Obstetrics and Gynaecology ', 'Successful Oocyte Cryopreservation with Random Start Protocol in a Patient with Hodgkin Lymphoma with a Mediastinal Mass- A Case Report'),
	(24, 'SR', 'SR#12', 'Dr. Upendra Singh Bhadauria, Senior Resident, Department of Division of Public Health Dentistry, CDER-AIIMS', 'A bibliometric analysis and visualization of the top 100 most cited articles in top 10 highest impact factor journals of nutrition and dietetics'),
	(25, 'SR', 'SR#13', 'Aparna Krishna, Senior Resident, Departments of Transfusion medicine', 'Prospective Observational Study Of Transfusion Practices In Severely Injured Trauma Patients In Emergency Department At Level 1 Trauma Center'),
	(26, 'SR', 'SR#14', 'Poornima Diana Ranganathan, Senior Resident, Department of, Department of Anaesthesiology, Pain Medicine and Critical Care', 'Predictors Of Blood Loss And Transfusion Requirement In Adolescent Idiopathic Scoliosis: A Multi Variate Regression Study Involving 132 Patients'),
	(27, 'SR', 'SR#15', 'Amiteshwar Singh, Senior Resident, Department of Medicine Science', 'FAVA: Mitigating delay by untangling the clinical quandary'),
	(28, 'SR', 'SR#16', 'Amolkumar Marotrao Lokade, Senior Resident, Department of ', 'Comparison of three protocols for the management of re-fracture of teeth with uncomplicated crown-root fractures: An In-vitro study'),
	(29, 'SR', 'SR#17', 'Sambit Sagar, Senior Resident, Department of ', 'Role of 18F-DOPA PET/CTimaging in adult patients with Hyperinsulinemic Hypoglycemia'),
	(30, 'SR', 'SR#18', 'Sambit Sagar, Senior Resident, Department of ', 'Utility of AI (Artificial Intelligence) tool for automatic segmentation and calculation of quantitative PET parameters compared to conventional manual segmentation in patients of Hodgkin’s Lymphoma'),
	(31, 'SR', 'SR#19', 'Dikhra Khan, Senior Resident, Department of ', 'In vivo assessment of somatostatin receptor expression with 68Ga-DOTANOC PET/CT in Graves’ ophthalmopathy'),
	(32, 'SR', 'SR#20', 'Dikhra Khan, Senior Resident, Department of ', 'Exploring the clinical ambit of 99m Tc Ubiquicidin scintigraphy'),
	(33, 'SR', 'SR#21', 'Dikhra Khan, Senior Resident, Department of ', '18F-FDG PET/CT in Pyrexia of unknown origin: Steering force from unknown to known'),
	(34, 'SR', 'SR#22', 'Neha Singh, Senior Resident, Department of Onco-anaesthesia and Palliative Medicine', 'Assessment of Symptom Burden and Quality of Life in Patients of Advanced Breast Cancer in Indian Population: A Cross Sectional Study'),
	(35, 'SR', 'SR#23', 'Dr. Ankita Sethi, DM / MCh, Senior Resident, Department of Obstetrics and Gynaecology', 'Implementation of Non-Invasive Preimplantation Genetic Testing for Aneuploidies (NIPGT-A) using Next-Generation Sequencing (NGS) on Spent Culture Media'),
	(36, 'SR', 'SR#24', 'Nikhil Mehta, Senior Resident, Department of ', 'Performance of Artificial Intelligence-driven mobile application in image diagnosis of venereal and non-venereal genital and peri genital lesions'),
	(37, 'SR', 'SR#25', 'Vandana Vijayeta Kiro, Senior Resident, Department of Microbiology, JPNATC', 'Epidemiology and characterization of Beta hemolytic streptococci in trauma patients. '),
	(38, 'SR', 'SR#26', 'Dr Mrudula Prasanna, DM / MCh, Senior Resident, Department of Anaesthesiology, Pain Medicine and Critical Care Medicine', 'Comparison of clinical efficacy of intrathecal 0.75% isobaric ropivacaine with fentanyl vs clonidine as adjuvants in caesarean section: a prospective randomised controlled trial'),
	(39, 'SR', 'SR#27', 'Yokasekar Venkatesan, Senior Resident, Department of Anaesthesiology, Pain medicine and Critical care', 'Ultrasound-Guided Erector Spinae Plane Block For Postoperative Analgesia In Patients Undergoing Percutaneous Nephrolithotomy – A Double-Blinded, Randomized Controlled Trial'),
	(40, 'SR', 'SR#28', 'Shivangi Dagar, Senior Resident', 'Comparative evaluation of microsatellite instability, immune microenvironment and molecular stratification of upper and lower tract urothelial carcinoma'),
	(41, 'SR', 'SR#29', 'Apoorva Praveen Kabra, Senior Resident, Department of Orthopaedics AIIMS', 'Predictors for postoperative ICU stay in pediatric patients (10-19years) with scoliosis- a retrospective study.'),
	(42, 'SR', 'SR#30', 'Dr. Karthik Ram. A, DM / MCh, Senior Resident', 'Efficacy Of Thoracic Fluid Content By Cardiometry In Predicting Weaning Failure In ICU- A Prospective Observational Study'),
	(43, 'SR', 'SR#32', 'Rajathadri Hosur Ravikumar, DM / MCh, Senior Resident, Department of anaesthesiology pain medicine and critical care', 'Ultrasonographic Assessment Of Brachial Artery Reactivity As Predictor Of Adverse Outcome In Patients Undergoing Emergency Laparotomy For Perforation Peritonitis: Prospective Case Control Study '),
	(44, 'SR', 'SR#33', 'Rajathadri Hosur Ravikumar, Senior Resident, (DM critical care medicine), Department of anesthesiology pain medicine and critical care ', 'Predictors Of Intensive Care Unit Admission And Mortality In Acute Febrile Illness: A Prospective Observational Study'),
	(45, 'SR', 'SR#34', 'Deepali Gupta, Senior Resident, Department of ', 'Identification and Biochemical characterization of novel anticancerous molecules against human Aurora kinase (AURKs) family of proteins'),
	(46, 'SR', 'SR#35', 'Poornima Diana Ranganathan, Senior Resident, Department of, Department of Anaesthesiology, Pain Medicine and Critical Care', 'Does Preoperative Oral Fluid Replenishment/Loading Affect Perioperative Volume Status? A Prospective Observational Study Using Ivc Collapsibility Index As Objective Parameter To Measure Volume Status In Patients With Pheochromocytoma And Paraganglioma Undergoing Surgical Tumor Removal'),
	(47, 'SR', 'SR#36', 'Dr Baby Pegu, Senior Resident, Department of ', 'Bilateral Ultrasound Guided Erector Spinae Plane Block For Postoperative Pain Relief In Traumatic Spine Surgery: A Randomised Controlled Trial'),
	(48, 'SR', 'SR#37', 'Divya Hirolli, DM / MCh, Senior Resident, Department of Critical Care Medicine ', 'Prognostic significance of red blood cell transfusion trigger in critically ill patients with sepsis or septic shock: A Prospective Observational Study'),
	(49, 'SR', 'SR#38', 'Dr. SEHAJ ROOP KAUR, Senior Resident, Department of RHEUMATOLOGY', 'Tofacitinib Treatment In Spondyloarthritis'),
	(50, 'SR', 'SR#39', 'Kiran Jot, Senior Resident, Department of Oral Pathology and Microbiology, Centre of Dental Education and Research,', 'Assessment of MUC5AC and MUC2 immunoexpression in glandular odontogenic cysts, dentigerous cysts with mucus metaplasia and mucoepidermoid carcinomas.'),
	(51, 'SR', 'SR#40', 'Dr. SEHAJ ROOP KAUR, Senior Resident, Department of RHEUMATOLOGY', 'Post Covid-19 Auto-Immune Rheumatic Diseases (Airds) And Outcome: A Tertiary Care Centre Experience'),
	(52, 'SR', 'SR#41', 'Jasper Rathinam, DM / MCh, Senior Resident, Dept of Anesthesiology, Pain Medicine and Critical Care', 'Effects Of Parenteral Omega 3 Fatty Acid Supplementation On Clinical Outcomes And Organ Failure In Acute Pancreatitis - A Randomised Controlled Trial '),
	(53, 'SR', 'SR#42', 'Neha Sharad, Senior Resident, 1., Department of Microbiology', 'Trend of Enterococcal infections during COVID-19 pandemic and the pre-pandemic period'),
	(54, 'SR', 'SR#43', 'Kavitha Girish, Senior Resident, Department of Anaesthesiology, Pain Medicine & Critical Care', 'Comparison of blind tracheal intubation through Air-Q and LMA Blockbuster in adults undergoing elective surgery: A randomized controlled trial'),
	(55, 'SR', 'SR#44', 'Sharin Varma, Senior Resident, Dept. of Microbiology ', 'Secondary Infections inhospitalised covid 19 patients: an unwelcome repercussion'),
	(56, 'SR', 'SR#45', 'Sayoni Roy Chowdhury, DM / MCh, Senior Resident, Department of Paediatrics', 'Remediating Indian school going children having specific learning disorder with dyslexia using artificial intelligence based structured intervention program'),
	(57, 'SR', 'SR#46', 'Smriti Srivastava, Senior Resident, Department of Microbiology, Trauma centre', 'Application of BioFireFilmArray Pneumonia Panel in critically ill culture-negative patients'),
	(58, 'SR', 'SR#47', 'Smriti Srivastava, Senior Resident, Department of Microbiology, Trauma centre', 'Diagnosis and Risk factors in Candida auris infections: A Retrospective study'),
	(59, 'SR', 'SR#48', 'Vivek Nayyar, Senior Resident, Department of Oral Pathology and Microbiology', 'Diagnostic utility of SATB2 and Ki-67 in differentiating osteosarcoma and juvenile ossifying fibroma occurring in the gnathic bone'),
	(60, 'SR', 'SR#49', 'Dr Rishi, DM / MCh, Senior Resident, Department of Pediatrics', 'Analysis of predictors of response to hormonal therapy in children with treatment naïve West syndrome with EEG, fMRI, qEEG and serum Biomarkers: An observational study'),
	(61, 'SR', 'SR#50', 'Kalung Manisha, Senior Resident, Department of ', 'Corrected Flow Time Measurement in Carotid and Brachial Artery To Assess Fluid Responsiveness in Spontaneously Breathing Patients: An Interventional Study'),
	(62, 'SR', 'SR#51', 'Dr. Soham Banerjee, Senior Resident, Departments of Radiodiagnosis', 'Comparison of Dual-Energy Computed Tomography (DECT) and Multiparametric Magnetic Resonance Imaging (mpMRI) Derived Perfusion Parameters for Characterization of Renal Cell Carcinoma (RCC)'),
	(63, 'SR', 'SR#52', 'Rani Kumari Gupta, Senior Resident, Department of ', 'A Retrospective Study To Evaluate The Crestal Bone Level AroundImmediate Implants Placed Using Socket Shield Technique And Conventional Technique'),
	(64, 'SR', 'SR#53', ' Dr. Mohak Narang, Senior Resident, Departments of 1Radiodiagnosis and Interventional Radiology ', 'Dual-energy CT and Multiparametric MRIbased imagingmarkers forgrading the severityof chronic pancreatitis usingquantificationof pancreatic fibrosis'),
	(65, 'SR', 'SR#54', 'Heena Parihar, Senior Resident, Department of Physiology', 'Transpinal motor evoked potential (TsMEP): A novel technique to differentiate positional loss of motor function of the spinal cord from failure to obtain baseline Transcranial motor evoked potential (TcMEP)'),
	(66, 'SR', 'SR#55', 'Dr.Bhanu Pratap Maurya, Senior Resident, Department of Oncoanaesthesia and Palliative Medicine Dr. BRA IRCH ', 'End-of-Life Care Practices at a Tertiary Care Cancer Centre in India: An Observational Study '),
	(67, 'SR', 'SR#56', 'Preet Hathi, DM / MCh, Senior Resident, Department of ', 'Pecuniary and Social Consequences of Trauma and Burns - Measuring the inapparent Health Expenditure'),
	(68, 'SR', 'SR#58', 'gautham chandran, DM / MCh, Senior Resident, Department of ', 'Efficacy of Diaphragmatic Tissue Doppler Imaging Parameters in predicting weaning outcomes in critically ill Adults'),
	(69, 'SR', 'SR#59', 'Dr Girish Jeer, Senior Resident, Department of ', 'Development and validation of the eHealth literacy scale for college students aged 18-24 years, Faridabad, India.'),
	(70, 'SR', 'SR#60', 'DR. BHAWESH PANGARIA, Senior Resident, Department of ', 'Assessment of symptom burden and quality of life in paediatric cancer patients in a tertiary care centre in India'),
	(71, 'SR', 'SR#61', 'Sachin Gupta, Senior Resident, Department of Dermatology and Venereology', 'Evaluation of a paraffin-based moisturizer as compared to a ceramide-based moisturizer in children with atopic dermatitis: a double blinded two group equivalence randomised controlled trial'),
	(72, 'SR', 'SR#62', 'Nihar Ameta, DM / MCh, Senior Resident, Department of Cardiac Anaesthesia and Critical Care', 'Comparison of the effects of different anaesthetic agents on cardiac electrophysiology parameters in adult cardiac patients undergoing radiofrequency ablation for supra-ventricular tachyarrhythmias'),
	(73, 'SR', 'SR#63', 'Dr. Sundara Kannan, DM / MCh, Senior Resident, Department of Anaesthesiology, Pain medicine and Critical care', 'Role Of Parasternal Intercostal Muscle Ultrasound During Weaning From Mechanical Ventilation And Prediction Of Extubation Success In ICU – A Prospective Observational Study'),
	(74, 'SR', 'SR#64', 'Rhea Ahuja, Senior Resident, 1Department of Dermatology and Venereology', 'Skin as a window toabrupt onset dysglycemia'),
	(75, 'SR', 'SR#65', 'KUMAR SANJEEV, Senior Resident, Department of Onco-Anaesthesia and Palliative Medicine,', 'Assessment of Symptom Burden and Quality of Life in Patients of Lung Cancer Attending the Palliative Care Clinic of a Tertiary Care Centre: A Prospective Observational Study'),
	(76, 'SR', 'SR#66', 'Khan Salman, Senior Resident, ', 'Evaluation of direct antibiotic susceptibility testing of Gram-negative bacilli from positive blood cultures bottles'),
	(77, 'SR', 'SR#67', 'Dr ABHIJITH K ANIL, Senior Resident, Department of Physiology', 'Diagnosis And Biofeedback Treatment Of Rumination Syndrome In Adults: Two Novel Approaches'),
	(78, 'SR', 'SR#68', 'GAUTAM KAMILA, DM / MCh, Senior Resident, Department of Pediatrics', 'Cortical Excitability and Thalamic volumetry in children with Electrical Status Epilepticus in Sleep (ESES)'),
	(79, 'SR', 'SR#69', 'Ankit Kumar Meena, DM / MCh, Senior Resident, Department of Pediatrics', 'Efficacy of repetitive transcranial magnetic stimulation (rTMS) therapy in Electrical status epilepticus in sleep syndrome (ESES) in children: A single arm intervention study'),
	(80, 'SR', 'SR#70', 'Hena Khandakar, Senior Resident, Department of Pathology', 'Comparative evaluation of PD-L1 status and immune microenvironment in molecular subtypes of muscle invasive bladder cancer'),
	(81, 'SR', 'SR#71', 'Dr Indradip Maity, Senior Resident, Department of Nephrology ', 'Characterisation of Chronic kidney disease of unknown origin in patients attending Nephrology OPD of AIIMS, New Delhi- A cross sectional study'),
	(82, 'SR', 'SR#72', 'Dr Indradip Maity, DM / MCh, Senior Resident, Department of Nephrology ', 'Evidence of heavy metal exposure in Chronic Kidney Disease of Unknown Origin - A Cross sectional study'),
	(83, 'SR', 'SR#73', 'SRAVAN NAGULAKONDA, DM / MCh, Senior Resident, Department of ', 'Cardiac Magnetic Resonance Imaging Using Native T1 Mapping Values To Identify Myocardial Fibrosis In Patients With Non-Ischemic Dilated Cardiomyopathy'),
	(84, 'SR', 'SR#74', 'Dr. Avichala Taxak, DM / MCh, Senior Resident, Department of Cardiovascular radiology and Endovascular Intevention', 'Randomized controlled trial evaluating the efficacy of trans-catheter genicular arterial embolization with knee pain in Kellgren-Lawrence grade II/III osteoarthritis refractory to optimal non-surgical management'),
	(85, 'SR', 'SR#77', 'Sivaraman Kumarasamy, Senior Resident, Department of Neurosurgery', 'Primary Calvarial and Spinal Ewing’s Sarcoma: A Case series'),
	(86, 'SR', 'SR#78', 'Keshav Agarwal, DM / MCh, Senior Resident, Department of Urology', 'Predicting tumour behaviour in Renal Cell Carcinoma using signature of molecular biomarkers (PRL3 phosphatase, CAV2, LAMA4 and GRP78'),
	(87, 'SR', 'SR#79', 'Dr Sivaraman Kumarasamy, Senior Resident, Department of Neurosurgery', 'Outcome Analysis of Surgical Management of Paediatric Cervical Kyphotic Deformity (CKD): an Institutional Experience'),
	(88, 'SR', 'SR#80', 'Dr. Arvinder, DM / MCh, Senior Resident, Department of ', 'Optimal duration for recording pediatric EEG: an observational study'),
	(89, 'SR', 'SR#81', 'Dr Timitrov P, DM / MCh, Senior Resident, Department of ', 'Transplant outcomes in patients with primary FSGS '),
	(90, 'SR', 'SR#82', 'Sai Krishna Kanukuntla (DM, Senior Resident), Department of ', 'Study On Effects Of Probiotics On Whole Gut Microbiome And Clinical Course In Patients With Critical Care Illnesses'),
	(91, 'SR', 'SR#83', 'Dr. Omar Afroz, Senior Resident, Department of ', 'Study on Concordance of ICD-11, ICD-10, and DSM-5 Diagnostic Guidelines for Alcohol and Opioid Use Disorders'),
	(92, 'SR', 'SR#84', 'Vasundhara Arora, DM / MCh, Senior Resident, Department of Cardiac Radiology and Endovascular Interventions', 'Roleof Non-contrast Dual Energy Cardiac CT in the detection of Diffuse Myocardial Fibrosis'),
	(93, 'SR', 'SR#85', 'Gargi Das, DM / MCh, Senior Resident, Department of Pediatrics ', 'Serum Adipokines As Biomarkers For Surveillance Of Metabolic Syndrome In Childhood Acute Lymphoblastic Leukemia/Lymphoma Survivors In Low Middle Income Countries: An Emerging Concept'),
	(94, 'SR', 'SR#86', 'Shreyam Acharya, Senior Resident, Department of Laboratory Medicine', 'Flow cytometric assessment of CD4+T and CD8+T cell subset populations in pulmonary tuberculosis patients with and without type 2 Diabetes mellitus'),
	(95, 'SR', 'SR#87', 'Debanjan Nandi, DM / MCh, Senior Resident, Department of ', 'Randomized control trial of great saphenous vein endovenous laser ablation using high and low energy 1940 nanometer radial fibre in patients with symptomatic varicose vein and saphenofemoral junction incompetence'),
	(96, 'SR', 'SR#88', 'Saranya B Gomathy, DM / MCh, Senior Resident, Department of ', 'A Randomised Controlled Trial Comparing The Efficacy Of Brief Psychoeducation Vs Yoga Nidra In Persons With Psychogenic Non-Epileptic Seizures'),
	(97, 'SR', 'SR#89', 'Ankesh gupta, DM / MCh, Senior Resident, Department of ', 'Audit for antifungal treatment usage in adults with invasive fungal infection: A prospective observational study'),
	(98, 'SR', 'SR#90', 'Deepak GP, DM / MCh, Senior Resident, Department of Neuroanaesthesiology and critical care', 'Comparison of change in the Pulsatality index before and after ventriculoperitoneal shunt surgery in adult patients with hydrocephalus'),
	(99, 'SR', 'SR#91', 'Mulaokar Mangesh Ganesh, Senior Resident, Department of Neuroanaesthesiology and critical care', 'Comparative study of automated quantitative pupillometry and clinical pupillometry in neurocritical care'),
	(100, 'SR', 'SR#92', 'Chawnchhim Abraham Lalchhana, DM / MCh, Senior Resident, Department of Neuroanaesthesiology & Critical Care', 'Comparison Of Glasgow Coma Scale, Full Outline Of Unresponsiveness And Glasgow Coma Scale-Pupils Score For Predicting Outcome In Patients With Traumatic Brain Injury '),
	(101, 'SR', 'SR#93', 'Madiwalesh Chhebbi, DM / MCh, Senior Resident, Department of Surgical Oncology', 'Narrow Band Imaging - A Promising Tool for Evaluation and Assessment of Oral Cavity Malignancies'),
	(102, 'SR', 'SR#94', 'Dr Sudeshna Padhi, DM / MCh, Senior Resident, Department of ', 'A randomized control trial to evaluate the effects of Ketofol and Propofol on cerebral oxygenation in patients undergoing Trans-sphenoidal pituitary surgery under total intravenous anaesthesia'),
	(103, 'SR', 'SR#95', 'Radhika Sarda, DM / MCh, Senior Resident, Department of ', 'Incidence and risk factors of Anti-tubercular Drug Induced liver injury: a prospective observational study at tertiary care centre in India'),
	(104, 'SR', 'SR#96', 'Shubham Mehta, DM / MCh, Senior Resident, Department of ', 'Impact of delay in the diagnosis on the severity of celiac disease'),
	(105, 'SDG', 'SDG#01', 'V Deepak Bamola Scientist 2, Department of Microbiology', 'Development of Indigenous Probiotics for Promoting Good Health and Wellbeing by Preventive and Therapeutic Applications (SDGs)'),
	(106, 'SDG', 'SDG#02', 'Leena Sapra Associate Professor, Department of Biotechnology', '“B-10” regulatory B cells (Bregs) suppress osteoclastogenesis and ameliorates inflammatory bone loss under post-menopausal osteoporotic conditions'),
	(107, 'SDG', 'SDG#03', 'Vinayaraj. E V, Phd Student, Department of Microbiology', 'Identifying and preventing Legionnaires\' disease: sustainable development goal 6 (SDG-6): Clean water and sanitation'),
	(108, 'SDG', 'SDG#04', 'Swarnabha Sarkar, Phd Student, Department of ', 'To study the effect of diesel exhaust exposure on the male reproductive health in laboratory rat using a self-fabricated whole body exposure unit: a concept based innovation (SDG)'),
	(109, 'SDG', 'SDG#05', 'khushwant singh, Phd Student, Department of Biochemistry', 'Combating on two fronts: cancer cells and weakened immune systems United Nations Sustainable Development Goals (UN SDGs)'),
	(110, 'SDG', 'SDG#06', ' Indrani Mukherjee Fellow, Department of Biochemistry', 'Estrogen Treatment Repudiates The Detrimental Effects Of Oxidative Stress In Cellular Models Of Preeclampsia (SDGs)'),
	(111, 'SDG', 'SDG#07', 'Dr Jasmin Bulbul, Senior Resident, Dept of Anaesthesiology pain medicine and critical care', 'Comparison Of Ketamine And Dexmedetomidine Infusions As Non-Opioid Anaesthetic Technique During Laparoscopic Bariatric Surgery: A Randomized Clinical'),
	(112, 'SDG', 'SDG#08', 'DR MANOJ KUMAR Scientist 2, Department of Laboratory Medicine, Jai Prakash Narayan Apex Trauma Centre, AIIMS', 'Dynamic Pattern of Granulocyte colony stimulating factor among trauma hemorrhagic shock patients'),
	(113, 'SDG', 'SDG#09', 'Deepika kumari, Phd Student, Department of Anatomy', 'Yoga- An AdjunctTherapy in Management of Polycystic Ovarian Syndrome (PCOS): A Pilot Study'),
	(114, 'SDG', 'SDG#10', 'Priyanka Gautam Other, Department of Neurology', 'Cost-effective analysis of evidence-based interventions underlying Acute Ischemic Stroke: A Retrospective Study of Patients in a Tertiary Care Hospital, Delhi, India.'),
	(115, 'SDG', 'SDG#11', 'Manish Tripathi, Phd Student, Department of ', 'Synthetic fuel, the fuel of future: an innovative approach for pollution abatement'),
	(116, 'SDG', 'SDG#12', 'Nisha Rathor Scientist 2, Department of Microbiology', 'Stewardship to overcome Antimicrobial Resistance: A step forward to achieve SDG-3 and SDG-1'),
	(117, 'SDG', 'SDG#13', 'Ashu singh, Phd Student, Department of Biochemistry', 'Ubiquitin mediated regulation of autophagyin memory T cells of Renal cell carcinoma: therapeutic target'),
	(118, 'SDG', 'SDG#14', 'HEMLATA RAI Other, Department of Laboratory Oncology', 'Designing of unmodified Gold Nanoparticles and Peptide Nucleic Acid based biosensor for detection of KIT D816Vvariantin plasma-derived circulating tumor DNA in Acute Myeloid Leukemia'),
	(119, 'SDG', 'SDG#15', 'Manisha bansal Fellow, Department of Anatomy', 'Impact of Yoga intervention on Mitochondrial functionality, vision and Quality of life in LHON cases'),
	(120, 'SDG', 'SDG#16', 'Brijesh Kumar, Phd Student, Department of Pediatrics', 'Fat and fat-free mass in term small for gestational age infants at birth and 6 months: Effect of catch-up growth'),
	(121, 'SDG', 'SDG#17', 'Apoorva Challa, Phd Student, Department of Dermatology and Venereology', 'The intimate story: Causes, components and characteristics of vaginal dysbiosis (SDG)'),
	(122, 'SDG', 'SDG#18', 'Anjali Yadav, Phd Student, Department of ', 'Male infertility and increased risk of cancer: Role of Yoga'),
	(123, 'SDG', 'SDG#19', 'SRISHTY RAMAN, Phd Student, Department of ', '[SDG] Citrate-capped gold nanoparticles based calorimetric sensor array for identification of toxic metal ions in water'),
	(124, 'SDG', 'SDG#20', 'Urvashi B Singh Professor, Department of Microbiology', 'Strides towards Sustainable Development Goals on the road toTuberculosis Control and Elimination in India'),
	(125, 'SDG', 'SDG#21', 'Deepak Kochar, Phd Student, Department of Microbiology ', 'An integrated intervention to reduce the prevalence of UTI among females belonging to lower socioeconomic status in community settings of India (SDG)'),
	(126, 'SDG', 'SDG#22', 'Masroor Anwar, Phd Student, Department of Geriatric Medicine', 'Establishment of Good health and Well-Being- A Geriatric Prospective”'),
	(127, 'SDG', 'SDG#23', 'Sonakshi Gupta, Phd Student, Dept of Microbiology', 'Screening for environmental existence of azole resistant Aspergillus fumigatus isolates in North India (SDG)'),
	(128, 'SDG', 'SDG#24', 'SONU Tyagi, Department of Microbiology, AIIMS, New Delhi', 'Antimicrobial Resistance a Silent Pandemic: Lessons to tackle a pandemic from COVID-19 management'),
	(129, 'PF', 'PF#01', 'Dr. Bhanu Priya Awasthi, Department of Biochemistry', 'Interaction of cytoskeleton with Mitochondria in Cancer: Is There Any Connection'),
	(130, 'PF', 'PF#02', 'Dr Manali Deb Barma, Department of CDER', 'Impact of war on oral health among children: A systematic review'),
	(131, 'PF', 'PF#03', 'Aliya Mufti, Department of Physiology', 'Cortical Transcranial Magnetic Stimulation a Promising Biomarker and therapeutic modality to induce Synaptic Plasticity in Cerebral Palsy Children with Single and Paired Pulses Paradigm'),
	(132, 'PF', 'PF#04', 'Stuti Gupta, Department of Laboratory Medicine, Jai Prakash Narayan Apex Trauma Center ', 'Prospective surveillance of Ventilator associated pneumonia in a network of hospitals in India: epidemiological profile, etiology and antibiogram'),
	(133, 'PF', 'PF#05', 'Stuti Gupta, Department of Laboratory Medicine, Jai Prakash Narayan Apex Trauma Center ', 'Evaluation and strengthening of infection control practices and antimicrobial stewardship in nursing homes and district hospitals of north India'),
	(134, 'PF', 'PF#06', 'Kumari Binita Chandra, Department of Biophysics', 'Fibroblast growth factor 8 (FGF8) knockdown slows down the progression of ovarian cancer'),
	(135, 'PF', 'PF#07', 'Dr. Surya Prakash Bhatt, Department of Pulmonary, Critical Care and Sleep Medicine', 'Prevalence of obstructive sleep apnea in commercial vehicle drivers and its correlation with road traffic accident and metabolic syndrome: A cross-sectional study.'),
	(136, 'PF', 'PF#08', 'Surya Prakash Bhatt, Department of Pulmonary, Critical Care and Sleep Medicine', 'Effect of Kallikrein-1, uromodulin, urocotin-3, and orosomucoid-1 markers in obese children with obstructive sleep apnea: A case control study.'),
	(137, 'PF', 'PF#09', 'Dr. Shilpi Malhotra, Department of Microbiology', 'Whole cell based aptamer selection for potential POCT for Neisseria gonorrhoeae'),
	(138, 'PF', 'PF#10', 'Dr.Shamima Akhtar, Department of Biochemistry', 'Autophagy-regulated Sialin (SLC17A5) protein aidsendothelial dysfunction by affecting nitrate flux'),
	(139, 'PF', 'PF#11', 'Sharad Srivastav  Jai Prakash Narayan Apex Trauma Center', 'Trend of Blood Stream Infections and Antimicrobial Resistance: Results from the existing surveillance network on healthcare associated infections'),
	(140, 'PF', 'PF#12', 'Mamta Puraswani Jai Prakash Narayan Apex Trauma Center', 'Health care associated infections in COVID ICU’s: a multicentric study'),
	(141, 'PF', 'PF#13', 'Dr. PRADEEP KUMAR, Department of NMR', 'Identification of metabolic changes associated with metastatic prostate cancer using NMR metabolomics'),
	(142, 'PF', 'PF#14', 'Shivalika Sharma Bahukhandi, Department of NMR ', 'NMR-based metabolomics for prostate cancer detection'),
	(143, 'PF', 'PF#15', 'Dr. Biswas Amitabh, Department of Orthopaedics', 'Whole-Exome Sequencing Reveals Potential Susceptibility Genes For Knee Osteoarthritis'),
	(144, 'PF', 'PF#16', 'Dr. Sonam Agarwal, Department of Biochemistry', 'Elucidate the efficacy of β-defensin 2 on M1 macrophages and their antitumor function in breast cancer'),
	(145, 'PF', 'PF#17', 'Dr Thejas Achary M G, Department of Centre for Community Medicine', 'Mild Cognitive Impairment among elderly persons residing in an urban resettlement colony in Delhi'),
	(146, 'PF', 'PF#18', 'Dr. SUNIL KUMAR, Department of Biotechnology', 'Selection of appropriate reference genes for normalization of qRT-PCR based gene expression analysis in SARS-CoV-2, and Covid-associated Mucormycosis infection'),
	(147, 'PF', 'PF#19', 'Dr. Namrata Kushwaha, Department of Biotechnology', 'Characterization of L,D-transpeptidase from Mycobacterium abscessus: An Emerging Opportunist Pathogen'),
	(148, 'PF', 'PF#20', 'Prachi Tewari, Department of Jai Prakash Narayan Apex Trauma ', 'Caesarian Section Surgical Site Infection Surveillance Using Standard Protocol in a Network of Tertiary Care Hospitals, India-2021'),
	(149, 'PF', 'PF#21', 'RASNA PARVEEN, Department of Jai Prakash Narayan Apex Trauma Center', 'Mentoring for implementation of Quality Improvement strategies to reduce the prevalence of Healthcare Associated Infection in a network of tertiary care hospitals in India'),
	(150, 'PF', 'PF#22', 'Bijay Ranjan Pattnaik, Department of Pulmonary, Critical Care & Sleep Medicine', 'Discrimination of two airway diseases by miRNAs in exhaled breath condensate: A pilot study'),
	(151, 'PF', 'PF#23', 'Bijay Ranjan Pattnaik, Department of Pulmonary Critical Care & Sleep Medicine, ', 'Clinical Evaluation of Pleural Effusion in Sarcoidosis patients in a tertiary care center'),
	(152, 'PF', 'PF#24', 'Dr. Bimal Prasad Jit, Department of Biochemistry', 'POTEE protein: A member of POTE (Prostate, Ovary, Testis and Embryo) family enhances Notch signaling and regulates ovarian cancer phenotype'),
	(153, 'PF', 'PF#25', 'Ruchi, Department of Biochemistry', 'The Synergism of RNA-binding Proteins, Insulin-like Growth Factor-2 Binding Proteins 1 and 3 (IGF2BP1/3) and Methyl-like transferases 3 and 4, (METTL3/14) in enhancing mRNA stabilityof their target genes'),
	(154, 'PF', 'PF#26', 'Shraddha Kapoor, Department of Biochemistry', 'Deciphering anti-cancer action of herbal drug Habb-e-Asgandh against Multiple myeloma using in-vitro cell line model'),
	(155, 'PF', 'PF#27', 'BIBHUDUTTA MISHRA, Department of Gastroenterology and Human Nutrition', 'Finding small molecules to target SARS-CoV-2 3CL Protease'),
	(156, 'PF', 'PF#28', 'SWATI SINGH, Department of Neuropathology, Neurosciences Centre', 'Exploring the role of AKT1 E17K mutation in meningioma'),
	(157, 'PF', 'PF#29', 'Dr Kriti Kaushik, Department of Biochmistry', 'Role of Hypoxia in regulating IGF2BP3-bound circular RNAs in Cancer'),
	(158, 'PF', 'PF#30', 'Dr. Ravi Prakash Yadav, Department of Anatomy', 'Severe SARS-CoV-2 infection reveals the multiple types of syncytial cells in the BALF of COVID -19 patients'),
	(159, 'PF', 'PF#31', 'Sonam singh, Department of Dermatology and Venereology1', 'IL-23R, IL-12Band HLA-C genespolymorphisms and their association with psoriasis risk in North Indianpatients'),
	(160, 'PF', 'PF#32', 'SAUMYA DASH, Department of Stem Cell Facility', 'Facile 3D Composite Scaffold Supporting Stem Cell Differentiation For Superior Bone Regeneration: In-Vivo Study'),
	(161, 'PF', 'PF#33', 'Jatin Kumar Drall, Department of Biological Sciences and Engineering', 'Quantitative Analysis of Cadmium in Blood and Urine Samples using Trace Metal Analyzer (TMA)'),
	(162, 'PF', 'PF#34', 'Shikha Chaudhary, Department of Anatomy', 'Ultrastructure study of Bronchoalveolar secretion of COVID-19 patients'),
	(163, 'PF', 'PF#35', 'Ms. DEEKSHA PATEL, Department of College of Nursing', 'Effect Of Recorded Maternal Voice On Child’ S Cooperation And Pain Perception During Bone Marrow Examination- Adouble Blinded Randomized Controlled Trial'),
	(164, 'PF', 'PF#36', 'Dr. Vivek Dixit, Department of Orthopaedics', 'Assessment Of Bone Health In Transgender Population Of India: The ‘AIIMS Initiative’'),
	(165, 'PF', 'PF#37', 'Dr. Vivek Dixit, Department of Orthopaedics ', 'Application Of Quantitative Bone Scan Using Kbone Values To Identify Regional Bone Metabolism Changes In Postmenopausal Osteoporotic Women Treated Either With Alendronate Or Teriparatide'),
	(166, 'PF', 'PF#38', 'Dr. Vivek Dixit, Department of Orthopaedics', 'Comparison Of Yearly Zolendronic Acid Versus Weekly Alendronate In Indian Postmenopausal Women With Osteoporosis'),
	(167, 'PF', 'PF#39', 'MISBA MAJOOD, Department of Stem Cell Facility', 'Ultra-thin hydrogel nanosheets for promoting chondrogenesis in WJMSCs'),
	(168, 'PF', 'PF#40', 'Dr. V Deepak Bamola, Department of Microbiology', 'Effects ofa Probiotic Bacillus coagulansUnique IS-2 on gut microbiota and cytokines in Inflammatory Bowel Disease (IBD)'),
	(169, 'PF', 'PF#41', 'Shruti Mahapatra Departhemt Stem Cell Facility (DBT-Centre of Excellence for Stem Cell Research', 'Mesenchymal stromal cellExosome (MSC@Exo)-embellished implantable biomaterial construct for regenerative medicine'),
	(170, 'PF', 'PF#42', 'Nisha Rathor, Department of Microbiology', 'Isolation and characterization of a novel bacteriophage in the Fight against Multidrug-resistant Acinetobacter baumannii'),
	(171, 'PF', 'PF#43', 'Binata Marik, Department of Anatomy', 'Mutation screening by whole exome sequencing and genotype-phenotype correlation in patients with vitamin D dependent rickets'),
	(172, 'PF', 'PF#44', 'DR. RENU SINGH, Department of Anatomy', 'Analysis of polymorphisms, Expression and methylation status of Monoamine Pathway Genes in Alcohol Dependence'),
	(173, 'PF', 'PF#45', 'Indrani Mukherjee, Department of Biochemistry', 'Preeclampsia associated altered trophoblasts invasion and differentiation involves XBP1 mediated ER stress pathways: Emerging pathways for therapeutic intervention in PE'),
	(174, 'PF', 'PF#46', 'Trishala Mohan, Department of Obstetrics and Gynecology', 'Prevalence of depression and anxiety in gynaecological cancer survivors and its correlation with pain in survivors'),
	(175, 'PF', 'PF#47', 'Anshul Sharma, Department of of Anatomy ', 'Identification of the mutation spectrum in posterior polar cataract patients from North India'),
	(176, 'PF', 'PF#48', 'Tarang Gupta, Department of Obstetrics and Gynecology ', 'Endocrine disrupting chemicals in Pregnancy and their correlation with household & cooking Products'),
	(177, 'PF', 'PF#49', 'Shalini Sharma, Department of Biotechnology', 'Designing of medicated clothing with a long lasting anti-microbial action'),
	(178, 'PF', 'PF#50', 'Sushil Kumari Sangwan, Department of Anatomy', 'Molecular analysis of aqueous humor of Retinoblastoma patients'),
	(179, 'PF', 'PF#51', 'Ayaan Ahmad Departmetn of f Biotechnology', 'Amoxicillin improves the pathophysiology induced in mice on exposure to a high-fat diet by modulating the gut microbiota'),
	(180, 'PF', 'PF#52', 'Dr. Shivani Pasi, Department of Psychiatry and National Drug Dependence Treatment Centre (NDDTC)', 'Case studies: “Sentimental Analysis of legacy of Emotions shared by suicide completers on Social Media Using ML approach”'),
	(181, 'PF', 'PF#53', 'Kumari R Mankamna Lipid Metabolism Laboratory, Department of Biotechnology', 'Investigate the role of seipin transmembrane domains in sequestering triacylglycerol to facilitate lipid droplet biogenesis'),
	(182, 'PF', 'PF#54', 'Jayanth R Seshan, Department of Neuroanesthesiology and Critical Care, Neurosciences Center', 'Changes in regional cerebral oxygen saturation (rSO2) following surgical revascularization in Moyamoya disease'),
	(183, 'PF', 'PF#55', 'Dr Arpna Srivastava, Department of Neurology', 'Regulation of GABAA receptor subunit stoichiometry by microRNAs in focal cortical dysplasia (FCD)'),
	(184, 'PF', 'PF#56', 'Abhilasha Nayal, Department of Biophysics', 'Blood Based Tau & Phoshorylated Tau As A Non-Invasive Biomarker Of Dementia In Ageing'),
	(185, 'PF', 'PF#57', 'SARITA KUMARI, Department of Laboratory Oncology Unit, Dr. BRA-IRCH', 'Prognostic utility of key copy number alterations in T cell acute lymphoblastic leukemia'),
	(186, 'PhD', 'PhD#01', 'Sheikh Mohammad Umar, Department of Medical Oncology (Lab), Dr. BRA IRCH', 'β-catenin inhibitor i.e. XAV939 impairs aerobic glycolysis in Triple-Negative Breast Cancer (TNBCs)'),
	(187, 'PhD', 'PhD#02', 'Rajkumar Kulandaisamy, Department of Biophysics', 'Structural and Functional studies of Mycobacterium tuberculosis peptidyltRNA hydrolase with substrate analogue: A biophysical and computational approaches'),
	(188, 'PhD', 'PhD#03', 'Meenakshi Sharma, Phd Student, Department of Division of Forensic Pathology and Molecular DNA', 'Plausible Equilibrium State of Transcription Factors Olig-2 and PDGF-α Receptor in post-mortem brain tissue after traumatic brain injury'),
	(189, 'PhD', 'PhD#04', 'Meenakshi Sharma, Phd Student, Department of Division of Forensic Pathology and Molecular DNA', 'Post Mortem Time Gap for RNA Detection in COVID-19 Cadavers'),
	(190, 'PhD', 'PhD#05', 'Dr Mohit Chowdhury, Senior Resident, Department of Medicine ', 'Efficacy of LDBio Aspergillus ICT Lateral Flow Assay for Serodiagnosis of Chronic Pulmonary Aspergillosis'),
	(191, 'PhD', 'PhD#06', 'Poorva Bhargava, Phd Student, Department Pharmacology', 'Cardioprotective Effect Of Teriflunomide In An Experimental Model Of Myocardial Infarction'),
	(192, 'PhD', 'PhD#07', 'Fatima Samreen, Phd Student, Department of Pharmacology', 'Effect of motor imagery training on corticomotor excitability and pain status in Rheumatoid Arthritis: A fMRI-based Neurofeedback study'),
	(193, 'PhD', 'PhD#08', 'Dr.Shubham Misra, Phd Student, Department of Neurology', 'Subtyping strokes using blood based biomarkers: A proteomics approach'),
	(194, 'PhD', 'PhD#09', 'SHRUTI KAHOL, Phd Student, Department of Pathology', 'Targeting novel HUWE1 protein has tumor suppressive effects by modulating glucose metabolism in Triple Negative Breast Cancer'),
	(195, 'PhD', 'PhD#11', 'Vipra Sharma, Phd Student, Department of Biophysics', 'Label-free proteomics of oral mucosa tissue to identify potential biomarkers that can flag predilection of precancerous lesions to oral cell carcinoma'),
	(196, 'PhD', 'PhD#12', 'Sakshi Shukla, Phd Student, Department of ', 'Adipocyte size distribution predicts obesity metabolic Profile in Bariatric Surgery subjects'),
	(197, 'PhD', 'PhD#13', 'Deeksha Patel, Phd Student, Department of Physiology', 'Intermittent theta burst stimulation as a potential therapeuticstrategy for motor and sensory recovery in complete spinal cord injury patients'),
	(198, 'PhD', 'PhD#14', 'Swarandeep Singh, Phd Student, Department of Biochemistry', 'Structure & Immunogenicity of an HIV-1 Clade-C native like envelope trimer derived from a Pediatric Elite Neutralizer'),
	(199, 'PhD', 'PhD#15', 'Jyotsna Singh, Phd Student, Department of Neuropathology Laboratory', 'Comprehensive profiling of meningiomas to gain insight into the translational advances'),
	(200, 'PhD', 'PhD#16', 'Abhinay Kumar Singh, Phd Student, Department of Biophysics ', 'Inflammatory cytoskeleton signalling regime proteins: A plausible circulatory markers for metastatic breast cancer'),
	(201, 'PhD', 'PhD#17', 'Vishakha Hooda, Phd Student, Department of Biochemistry', 'Elucidating Natural Killer cells in the Immunopathogenesis of Pemphigus Vulgaris'),
	(202, 'PhD', 'PhD#18', 'Sonakshi Gupta, Phd Student, Department of ', 'A study of the ecology, evolution and resistance mechanism of C.auris'),
	(203, 'PhD', 'PhD#19', 'Ayushi Thapliyal Phd Stident, Department of Biophysics', 'Oxidative stress related sperm proteins contribute to idiopathic recurrent pregnancy loss'),
	(204, 'PhD', 'PhD#20', 'Abhinav Saini, Phd Student, 1Department of Biophysics', 'Multimerin 1 helps in the progression of ovarian cancer bytempering DNA damage response pathways'),
	(205, 'PhD', 'PhD#21', 'NEHA SINGH, Phd Student, ', 'Increased retention of nanoparticle in cells by a small molecule inhibitor'),
	(206, 'PhD', 'PhD#22', 'Chaithanya Leon, Phd Student, Department of Physiology', 'Resting EEG microstate as a candidate endophenotype in children with attention deficit hyperactivity disorder'),
	(207, 'PhD', 'PhD#23', 'Yudhishthir Yadav, Phd Student, Department of Biophysics', 'Neuroprotective role of Syzygium aromaticum on SIRT1 and oxidative balance in Alzheimer’s disease'),
	(208, 'PhD', 'PhD#24', 'Jayanti Jha, Phd Student, Department of Ocular Pathology', 'Role of melanocytic markers in uveal melanoma and its prognostic significance'),
	(209, 'PhD', 'PhD#25', 'NIKHIL KUMAR, Phd Student, Department of ', 'Association of YAP and PAX3 in Uveal Melanoma and its correlation with clinicopathological parameters'),
	(210, 'PhD', 'PhD#26', 'Ashu Singh, Phd Student, Department of Biochemistry', 'KCMF1 regulate autophagy and ion channels function in Renal Cell Carcinoma: A future therapeutic target'),
	(211, 'PhD', 'PhD#27', 'Komal Sagar, Phd Student, Department of Biochemistry', 'Dysfunctional MDSCs and Tregs contributes to atherosclerosis progression '),
	(212, 'PhD', 'PhD#28', 'Deeksha Madhry, Phd Student, Department of Biotechnology', 'RNases modulation and the generation of tRNA fragments (tsRNA) during DENV pathogenesis.'),
	(213, 'PhD', 'PhD#29', ' Naba Sami, Phd Student, Department of Physiology ', 'To study the effect of perturbation angle on learning using the Visuomotor adaptation task'),
	(214, 'PhD', 'PhD#30', 'Shweta Sharma, Phd Student, Department of Physiology', 'Effectiveness of probiotics intervention on motor and cognitive deficits in a 6-hydroxy dopamine rat model of Parkinson’s disease via modulation of brain-gut axis'),
	(215, 'PhD', 'PhD#31', 'Vishwa Rawat, Phd Student, Department of NMR', 'Gender-Specific Structural Changes in the Patients with Major Depressive Disorder (MDD): A MRI Study'),
	(216, 'PhD', 'PhD#32', 'Bhaskar Sharma, Phd Student, Department of Anatomy', 'Microglial activation in intense light-exposed retina selectively perturbed with Müller cell functions'),
	(217, 'PhD', 'PhD#33', 'NEHA AFARIA, Phd Student, Department of Forensic Medicine and Toxicology ', 'Analysis of Methanol in Blood, Vitreous Humor and Cerebrospinal Fluid using GC-HS - A Case Study'),
	(218, 'PhD', 'PhD#34', 'Mahaiwon Shadang, Phd Student, Dept. Of Biochemistry', 'PIH1D1 of co-chaperone PAQosome interacts with pRb of cell cycle to aid high risk HPV E7-mediated oncogenesis.'),
	(219, 'PhD', 'PhD#35', 'Sumedha Saluja, Phd Student, Department of Biochemistry', 'Exploring the interplay between N-6-methyladenosine (m6A) machinery and IGF2BP family of RNA Binding proteins in B-cell Acute Lymphoblastic Leukemia.'),
	(220, 'PhD', 'PhD#36', 'Neelam Upadhyay, Phd Student, Department of Biophysics,', 'Clinical Application Of Liquid Biopsy For Assessing Early Egfr Mutation Detection In Non-Small Cell Lung Carcinoma'),
	(221, 'PhD', 'PhD#37', 'Sonu Kumar, Phd Student, Department of Gastroenterology', 'Assessment of the Cell-Free DNAIntegrity Index and circulating tumor DNA hotspot mutation as an early prediction liquid biopsy marker for hepatocellular carcinoma'),
	(222, 'PhD', 'PhD#38', 'Amber Rathor, Phd Student, Department of Pathology', 'Clinical Application Of Liquid Biopsy For Assessing Early Egfr Mutation Detection In Non-Small Cell Lung Carcinoma'),
	(223, 'PhD', 'PhD#39', 'Amit Khatri, Phd Student, Department of ', 'Sterol ester containing lipid droplets originate at Seipin marked ER subdomains'),
	(224, 'PhD', 'PhD#40', 'Anjali Singh, Phd Student, Department of Biotechnology', 'Understanding modulation of gene regulatory mechanisms during Dengue virus pathogenesis'),
	(225, 'PhD', 'PhD#41', 'Shalini, Phd Student, Department of Pharmacology', 'Developing rat model of 5-fluorouracil induced cardiotoxicity'),
	(226, 'PhD', 'PhD#42', 'Asha Bhardwaj, Phd Student, Department of Translational Immunology', 'Lactobacillus acidophilus modulates the “GUT-Immune-Bone” axis and inhibits inflammatory bone loss in ovx mice via regulating intestinal pTregs'),
	(227, 'PhD', 'PhD#43', 'Devyani Sharma, Phd Student, Department of Anatomy', 'Interplay between autophagy and ferroptosis in photoreceptor apoptosis in aged iron-overloaded rats'),
	(228, 'PhD', 'PhD#44', 'AISHWARYA SINGH, Phd Student, Department of Biochemistry', 'Autophagyalleviates inflammatory milieu by modulating tumor-associated macrophages in Urothelial Carcinoma of Bladder'),
	(229, 'PhD', 'PhD#45', 'Divyanjali Rai, Phd Student, Department of Centre for Advanced Research and Education-ICMR, Breathomics in Respiratory Diseases Lab, Pulmonary, Critical Care & Sleep Medicine', 'miRNA profiling in Exhaled breath condensate for distinguishing Lung Cancer from COPD: A pilot study'),
	(230, 'PhD', 'PhD#46', 'Dhiraj Kumar Singh, Phd Student, Dept. Of Biochemistry AIIMS New Delhi.', 'Role of PIH1D1 Component of R2TP complex in cell cycle'),
	(231, 'PhD', 'PhD#47', 'David Raja, Phd Student, Department of Biochemistry', 'Characterisation of B regulatory subsets in Urothelial carcinoma of Bladder'),
	(232, 'PhD', 'PhD#48', 'CHETNA BANGA, Phd Student, Departments of NMR', 'Correlation of MR-based phenotyping with autonomic functions in healthy volunteers'),
	(233, 'PhD', 'PhD#49', 'Sadia Shah, Phd Student, Department of Pharmacolog', 'Differential effect of vitamin D in monocrotaline induced pulmonary arterial hypertension in normal and vitamin D deficient rats: Possible involvement of eNOS/TGF-β/α-SMA signaling pathways'),
	(234, 'PhD', 'PhD#50', 'Subhadip Kundu, Phd Student, Department of Biochemistry', 'Elucidation of the functional aspects and underlying epigenetic regulation of cancer-testis antigen POTE gene in ovarian cancer with the assessment of its immunotherapeutic potential '),
	(235, 'PhD', 'PhD#51', 'Rutumbara Dash, Phd Student, Department of Gastroenterology and Human Nutrition', 'Reverse genetic approach to develop models to study host immune response of SARS-CoV-2 using viral vectors'),
	(236, 'PhD', 'PhD#52', 'Leena Sapra, Phd Student, Department of Biotechnology', '“B-10” regulatory B cells (Bregs) suppress osteoclastogenesis and ameliorates inflammatory bone loss under post-menopausal osteoporotic conditions'),
	(237, 'PhD', 'PhD#53', 'Jaya Tak, Phd Student, Centre for Advanced Research and Education-ICMR, Breathomics in Respiratory Diseases Lab, Pulmonary, Critical Care & Sleep Medicine', 'Discrimination of pulmonary TB and extra-pulmonary TB from healthy subjects by smell prints in Indian population: A pilot study'),
	(238, 'PhD', 'PhD#54', 'Yashvi Sharma, Phd Student, Department of 1Stem Cell Facility', 'Hypoxia primed Wharton’s Jelly MSCs derived EVs exhibit enhanced immunosuppressive capabilities by virtue of their miRNA cargo as compared to Bone Marrow MSCs derived Evs'),
	(239, 'PhD', 'PhD#55', 'Sania Yasmin, Phd Student, Department of Anatomy', 'Characterization ofFlavin-based fluorescent LOV-domain protein for high-resolutionultra-structural studies'),
	(240, 'PhD', 'PhD#56', 'Khushwant Singh, Phd Student, Department of Biochemistry', 'Prolonged-release Of Docetaxel In 3D Tumor Microenvironment from HSP70 consolidated Docetaxel'),
	(241, 'PhD', 'PhD#57', ' Ashna Gupta, Phd Student, Department of Medical Oncology (Lab) BRAIRCH', 'Development of Liquid Biopsy HPV (Human Papilloma virus) cell free (cf) DNA based approach for diagnosis and prognosis of Cervical Cancer'),
	(242, 'PhD', 'PhD#58', 'Ankita Singh, Phd Student, Department of NMR', 'Proton NMR spectroscopy based chemosensory differentiation of anti-obesity phytochemicals and medicinal plants in tandem with anti-lipase assays'),
	(243, 'PhD', 'PhD#60', 'Apoorva Challa Phd Studnet, Department of Dermatology and Venereology', 'Correlation analysis of vaginal microbiome and metabolome to identify metabolite-based biomarkers of bacterial vaginosis.'),
	(244, 'PhD', 'PhD#61', 'Aphrodite Chakraborty, Phd Student, Department of Neurology', 'Novel GABAA receptor subunit variants may contribute to benzodiazepine resistance in patients with drug-resistant epilepsy'),
	(245, 'PhD', 'PhD#62', 'YOGESH AGGARWAL, Phd Student, Department of Biophysics', 'To understand the effect of tissue thickness on effectiveness of plasma jet in resected tumor tissues from glioma patients'),
	(246, 'PhD', 'PhD#63', 'Ashutosh Bansal, Phd Student, Department of Cardiac Biochemistry', 'Priming Endothelial Progenitor Cells (EPCs) with the Stem Cells: Emerging tool to combat Cardiovascular-Diseases (CVDs)'),
	(247, 'PhD', 'PhD#64', 'Arti Saini, Phd Student, Department of ', 'Genotype-Phenotype correlations in THAP1 dystonia in six Indian patients'),
	(248, 'PhD', 'PhD#65', 'Anandapadmanabhan R, Phd Student, Department of ', 'Machine learning algorithms for classificationand analysis of pen-on-paperArchimedesspirals'),
	(249, 'PhD', 'PhD#67', 'Poorvi Vishwakarma, Phd Student, Department of ', 'Structural studies of 1,4 β– xylosidase from Glycoside hydrolase family 43.'),
	(250, 'PhD', 'PhD#68', 'Gunjan Sharma, Phd Student, Department of Physiology', 'Standardization of intermittent theta burst stimulation paradigm and electrophysiological recordings in unanesthetized spinal cord injured rats'),
	(251, 'PhD', 'PhD#69', 'Sheetal Negi, Phd Student, Department of Biotechnology', 'Development of sensitive and specific probe that determines ▪NO production and quantifies Hydrogen sulfide mediated inhibition of ▪NO in living cells'),
	(252, 'PhD', 'PhD#70', 'Brijesh Kumar, Phd Student, Department of Pediatrics', 'Fat and fat-free mass in term small for gestational age infants at birth and 6 months: Effect of catch-up growth '),
	(253, 'PhD', 'PhD#71', 'sumaira Qamar, Phd Student, ', 'Resting energy expenditure and substrate utilization in patients with cirrhosis presenting with acute variceal bleeding'),
	(254, 'PhD', 'PhD#72', 'Mercilena Benjamin, Phd Student, Department of 1Laboratory Oncology', 'Prognostic Relevance of Surface Expression of CRLF2 in Pediatric Patients with B Cell Acute Lymphoblastic Leukemia'),
	(255, 'PhD', 'PhD#73', 'Ruchika Kaushik, Phd Student, Department of Forensic Medicine1', 'Genome Wide Association Study of Suicidal Deaths in India'),
	(256, 'PhD', 'PhD#74', 'Ruchika Kaushik, Phd Student, Department of Forensic Medicine1', 'Tumor Necrosis Factor-alpha (TNF-α) polymorphisms associated with Suicide: a case-control study'),
	(257, 'PhD', 'PhD#76', 'Shipra, Phd Student, Department of Cardiac Biochemistry', 'Downregulation of HMGB1 and HSP60 transcript levels in peripheral blood of dilated cardiomyopathy patients and it’s correlation with disease severity'),
	(258, 'PhD', 'PhD#77', 'BLESSED RAJ, Phd Student, Department of Biochemistry', 'Comparison of omental fat from obese and non-obese individuals by RNA seq indicates protease receptor F2RL3 in mediating insulin resistance'),
	(259, 'PhD', 'PhD#78', 'Kanchan Saini PhD Student', 'Oxalate compromises Cellular Bioenergetics and Redox Homeostasis in macrophages to exacerbate uropathogenic E. coli infection'),
	(260, 'PhD', 'PhD#80', 'E Pranshu Rao Rao, Phd Student, Department of ', 'Novel 3D Printing Strategy To Enhance Biomimicry of bioartificial Construct For bone regeneration'),
	(261, 'PhD', 'PhD#81', 'Zaffar Azam, Phd Student, Department of Biotechnology', 'Cissus quadrangularis inhibits osteoclastogenesis and ameliorates inflammatory bone loss under estrogen-deficient preclinical model of osteoporosis via modulating the host osteoimmune system'),
	(262, 'PhD', 'PhD#82', 'Pooja Yadav, Phd Student, Department of ', 'Primary culture and characterization of giant cell tumor of bone'),
	(263, 'PhD', 'PhD#83', 'Vivek Dubey, Phd Student, Department of Biophysics', 'Differential expression of sema 3F and sema 4C in the hippocampus and anterior temporal lobe (ATL) of pilocarpine model of temporal lobe epilepsy'),
	(264, 'PhD', 'PhD#84', 'Mohit Arora, Phd Student, Department of Biochemistry', 'Repurposing of DPP4 inhibitor vildagliptin in glioma: a potential temozolomide sensitizer.'),
	(265, 'PhD', 'PhD#85', 'Nisha Chauhan, Phd Student, Department of NMR', 'Effect of noise exposure on Neurometabolites in Wistar Rats: An in-vivo MRS study'),
	(266, 'PhD', 'PhD#86', 'Ankit, Phd Student, Department of Physiology', 'Brain cortical sources and connectivity of working memory in children with attention deficit hyperactivity disorder'),
	(267, 'PhD', 'PhD#87', 'Avanish Kumar Pandey, Phd Student, Department of Laboratory Oncology, Dr. B.R.A.I.R.C.H', 'Prognostic relevance of MN1 expression in cytogenetically normal adult AML patients'),
	(268, 'PhD', 'PhD#88', 'Pankaj, Phd Student, Departments of NMR', 'Cerebellar anatomical parcellation and volumetric changes in patients with Spinocerebellar ataxia type 2 and 12'),
	(269, 'PhD', 'PhD#89', 'ANSH GOSWAMI, Phd Student, Department of Pathology', 'A novel start loss variant in the MMP9 gene associated with familial hypertrophic cardiomyopathy'),
	(270, 'PhD', 'PhD#90', 'AAFREEN KHAN, Phd Student, Department of ', 'Validation Of Gene Targets Identified By Single Cell Sequencing Of CD34+ Enriched Leukemic Cells In Pediatric AML'),
	(271, 'PhD', 'PhD#91', 'Christine Wilson, Phd Student, Department of Medical Oncology', 'Exploring The Significance Of Long Non-Coding Rna Hotairm1 In The Pathogenesis Of Paediatric Acute Myeloid Leukaemia'),
	(272, 'PhD', 'PhD#92', 'Bandana Jassal, Phd Student, Department of Neuropathology Laboratory, Neurosciences Centre', 'Prevalence and clinical correlation of myositis-specific and myositis-associated autoantibodies in Indian myositis cohort'),
	(273, 'PhD', 'PhD#94', 'Amit Kumar Yadav, Phd Student, Department of ', 'Identification of potential lead compounds targeting Mycobacterium tuberculosis shikimate kinase to combat multi-drug resistant tuberculosis'),
	(274, 'PhD', 'PhD#95', 'Vaishali Thukral, Phd Student, Department of ', 'Gut microbiota and gastrointestinal dysfunction in children with sepsis and septic shock'),
	(275, 'PhD', 'PhD#96', 'ATUL BASNAL, Phd Student, Department of Laboratory Oncology Unit, Dr. BRAIRCH ', 'Determination of somatic mutational landscape using panel based targeted next-generation sequencing to achieve deep coveragein newly diagnosed Multiple myeloma in anIndian cohort'),
	(276, 'PhD', 'PhD#97', 'Shivani Phd Studnet, Department of Anatomy', 'A transcriptomic study to evaluate the effects of Hydrogen sulphide post hypoxia/reoxygenation injury'),
	(277, 'PhD', 'PhD#98', 'Harshita, Phd Student, Department of ', 'Serum level of WT1 gene in the diagnosis of ovarian cancer'),
	(278, 'PhD', 'PhD#99', 'Kangana Aggarwal, Phd Student, Department of Forensic Medicine and Toxicology', 'Recovery Of Mitochondrial DNA From Burnt Tooth Samples'),
	(279, 'PhD', 'PhD#100', 'ANSH GOSWAMI, Phd Student, Department of Pathology', 'A novel start loss variant in the LMNA gene associated with familial dilated cardiomyopathy'),
	(280, 'NUR', 'NUR_01', 'Bibinlal.O 1, Sibi Riju 2, Deepak Agrawal 3, Smita Das 2', 'A cross sectional study to validate and assess the accuracy of a Three parameter nomogram in weight prediction and drug dose calculation for adult bed bound patients in AIIMS New Delhi.'),
	(281, 'NUR', 'NUR_02', 'Dr. Latha Venkatesan, Sibi Riju, Seema Sachdeva, Neeraja Bhatla, Aprana Sharma, Rakesh Garg', 'Obstetric CPR: Simulation Based skill training program for Labour room Nurses and its outcome'),
	(282, 'NUR', 'NUR_03', 'Vasundhara, Latha venkatesan, Cecilia M.S, Devendra Bajpai', 'A Study To Assess The Effectiveness Of Safe Discharge Program (SDP) On Knowledge And Skills Of Mothers In Homecare Management Of Surgical Neonates At SNICU, AIIMS, New Delhi'),
	(283, 'NUR', 'NUR_04', 'Rubi Zined, Rimple Sharma, Smita Das, Rajni Sharma', 'Physical Activity of Children with T1DM during Covid 19 Pandemic and it’s Impact on Glycemic Control'),
	(284, 'NUR', 'NUR_05', 'Manita Dalal', 'Attitude of Nurses towards Birth Companion Initiative'),
	(285, 'NUR', 'NUR_06', 'Monika Tanwar, Cecilia M.S, Rimple Sharma, Poonam Joshi, Anu Thukral', 'Breast feeding adequacy, behaviour and exclusivity in partially paladai fed and exclusive breast fed stable neonates'),
	(286, 'NUR', 'NUR_07', 'Ms Dhanya V A, Dr Rimple Sharma, Dr P Ramesh Menon, Dr L Gopichandran', 'Effect of Multi-component intervention program on post-operative care of infants undergoing cardiac surgery; evaluation of its effect on parents and infants'),
	(287, 'MSc', 'MSc#01', 'Swati Rohilla ', 'Revisiting the anatomical localization of transverse-sigmoid sinus junction with respect to the asterion.'),
	(288, 'MSc', 'MSc#02', 'Nandana Devi ', 'Effects of Catechins on Hormone Mediated Stromal-Epithelial Interaction in Prostate Cells'),
	(289, 'MSc', 'MSc#03', 'Sneha verma ', 'Analysis of anti-cancer activity of novel benzoxazole derivatives on prostate cancer cells'),
	(290, 'MSc', 'MSc#04', 'Shivi Khurana ', 'Effect of Circulating Exosomes, Isolated from Recurrent Pregnancy Loss (RPL) Women, on Trophoblast Cells'),
	(291, 'MSc', 'MSc#05', 'Mohd Hashim ', 'Quantification of whole body effective dose to radiation worker during manual synthesis of 188Re- labeled radiopharmaceuticals- A radiation protection based study'),
	(292, 'MSc', 'MSc#06', 'Mr. Deepanshu Vats ', 'Effect of repetitive transcranial magnetic stimulation of dorsolateral prefrontal cortex on pain status in phantom limb pain'),
	(293, 'MSc', 'MSc#07', 'Ms. Monika Kataria ', 'Effect of repetitive transcranial magnetic stimulation on pain status in post mastectomy pain syndrome '),
	(294, 'MSc', 'MSc#08', 'Sweety Rani ', 'Assessing involvement of the JAK-STAT cell signaling pathway in a cell-line model of oligodendrocyte differentiation in vitro'),
	(295, 'MSc', 'MSc#09', 'Jyoti ', 'Clinical feasibility of low activity whole body 18F-FDG PET/CT using conventional PET/CT scanner in Lymphoma patients'),
	(296, 'MSc', 'MSc#10', 'Anshika Pathak ', 'Optimization of % radiochemical purity (% RCP) and radionuclidic purity (RNP) assessment of therapeutic radiopharmaceutical by using well counter and gamma camera- An AIIMS radiopharmacy experience'),
	(297, 'MSc', 'MSc#11', 'Jagrati Chaudhary ', 'Improving Image Quality of 99m-Tc MDP bone scan images using Linear Point Operation'),
	(298, 'MSc', 'MSc#12', 'Gagandeep Kaur ', 'Improving Nuclear Medicine image quality using full-scale Histogram stretch'),
	(299, 'MSc', 'MSc#13', 'Yogesh Sharma ', 'Neuroinflammatory changes in the retina after light insult in Sprague- Dawley rats'),
	(300, 'MSc', 'MSc#14', 'Bhanupriya tanwar ', 'The role of mitochondrial VDAC and associated genes in pediatric B-cell acute lymphoblastic leukemia'),
	(301, 'MSc', 'MSc#15', 'Mili Kaur ', 'MicroRNA expression proﬁles in Sertoli cell only syndrome (SCOS) cases'),
	(302, 'MSc', 'MSc#16', 'Priya Yadav ', 'Logarithmic operation followed by a full-scale histogram stretch enhances the quality of planar bone scan images'),
	(303, 'MSc', 'MSc#17', 'Shivam Angiras ', 'Analysis of blood flow measurements in repaired Tetralogy Of Fallot(TOF) patients: comparison between 2D phase contrast Cardiac Magnetic Resonance and 4D phase contrast Cardiac Magnetic Resonance.'),
	(304, 'MSc', 'MSc#18', 'Sakshi Dogra ', 'Improved Visualisation of Renal Scar in Tc99m DMSA scan using Fuzzy Logic'),
	(305, 'MSc', 'MSc#19', 'Priyajit Kaur ', 'Glycogen Synthase Kinase 3-Beta as a Blood Based Biomarker for Early Detection of Alzheimer’s Disease.'),
	(306, 'MSc', 'MSc#20', 'Arunima Goswami ', 'Structural Modelling of Platelet Activating Factor Acetyl Hydrolase fromLeishmaniadonovani, Trypanosoma cruzi and Trypanosoma brucei:Implications on therapeutics for Leishmaniasis, Chagas Disease and Sleeping Sickness'),
	(307, 'MSc', 'MSc#21', 'Kumar Nischay Jaiswal ', 'Effect of somatotype on spirometry and aerobic exercise capacity'),
	(308, 'MSc', 'MSc#22', 'Harshita Mangla ', 'Effect of Exercise on Locomotor Performance in Low Thoracic Spinal Cord Injury Rat Model'),
	(309, 'MSc', 'MSc#23', 'Renu Kumari ', 'Influence of pH on the structure and function of human Aurora kinase B protein (hAURK-B) '),
	(310, 'MSc', 'MSc#24', 'Shuchita Saxena ', 'Effect of intermittent theta burst stimulation on heart rate variability in Parkinson’s disease patients'),
	(311, 'MSc', 'MSc#25', 'Ananya Kar ', 'A study of conditioned pain modulation in chronic pancreatitis'),
	(312, 'MSc', 'MSc#26', 'Sneha ', 'Effect of Mucuna pruriens in Parkinson’s disease'),
	(313, 'MSc', 'MSc#27', 'Aryan ', 'Altered expression of glypican 4 (Gpc4) and neuronal pentraxin 1 (NP1) in the hippocampus oftemporal Lobe Epilepsy (TLE)'),
	(314, 'MSc', 'MSc#28', 'Monika ', 'Breastfeeding adequacy, behaviour and exclusivity in partially paladai fed and exclusive breast-fed stable neonates'),
	(315, 'MSc', 'MSc#29', 'Rishabh Soni ', 'Fast spindle density during sleep correlates with psychomotor ability in good sleepers among older adults - a pilot study '),
	(316, 'MSc', 'MSc#30', 'Aparna Sharma ', 'A method to identify HPV-16 induced cervical cancer cells in routine Thin-prep cytology samples'),
	(317, 'MSc', 'MSc#31', 'Priti Singh ', 'Effect of chemotherapy on cognitive function in patients with breast cancer'),
	(318, 'MSc', 'MSc#32', 'Madhuri ', 'Screening of DrugBank to find potential lead molecules for design of drugs to shorten the treatment duration of tuberculosis'),
	(319, 'MSc', 'MSc#33', 'Pranav Panchbhai ', 'Effects of calcitriol pre-treatment in the restoration of right ventricular and renal function in an experimental model of cardio-renal syndrome in rats');
/*!40000 ALTER TABLE `posters` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
